# docker run -d -it -v /path/on/host:/data -e EULA=TRUE -e TYPE=FORGE -e VERSION=1.12.2 -e FORGE_VERSION=14.23.5.2854 -p 25565:25565 --name mc itzg/minecraft-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: mc
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
      - name: minecraft-data
      containers:
      - name: minecraft-server
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1.5Gi
        image: itzg/minecraft-server:latest
        env:
          - name:  EULA
            value: 'TRUE'
          - name: MODE
            value: 'survival'
          - name: MOTD
            value: "tfahlman's server"
          - name: TYPE
            value: 'SPIGOT'
        ports:
        - containerPort:  25565
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath:  /data
        readinessProbe:
          exec:
            command:
            - mc-monitor
            - status
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
            - mc-monitor
            - status
          initialDelaySeconds: 30
          periodSeconds: 30    